# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logRegApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_authors', to='logRegApp.Users')),
            ],
        ),
        migrations.CreateModel(
            name='BooksDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors_books', to='booksApp.AuthorsDB')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_books', to='logRegApp.Users')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_reviews', to='booksApp.BooksDB')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_reviews', to='logRegApp.Users')),
            ],
        ),
    ]
