# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='courses',
            name='desc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coursesApp.Description'),
        ),
    ]
